# 1) COSINE SIMILARITY:

In [11]:
import numpy as np

In [8]:
def cos_sim(a, b):

    dot_product = np.dot(a, b)
    norm_a = np.linalg.norm(a)
    norm_b = np.linalg.norm(b)
    return dot_product / (norm_a * norm_b)

In [9]:
sentence_1 = np.array([1, 1, 1, 1, 0, 0, 0, 0, 0]) 
sentence_2 = np.array([0, 0, 1, 1, 1, 1, 0, 0, 0])
sentence_3 = np.array([0, 0, 0, 1, 0, 0, 1, 1, 1])

In [10]:
print("The cosine similarity between sentence 1 and 2 is:\t"+str(cos_sim(sentence_1, sentence_2)))
print("The cosine similarity between sentence 2 and 3 is:\t"+str(cos_sim(sentence_2, sentence_3)))

The cosine similarity between sentence 1 and 2 is:	0.5
The cosine similarity between sentence 2 and 3 is:	0.25


# 2) STEMMING:

In [13]:
from nltk.stem import PorterStemmer 
from nltk.tokenize import word_tokenize

In [14]:
ps = PorterStemmer() 
words = ["program", "programs", "programer", "programing", "programers"]

In [20]:
def stemmer(wordlist):
    for w in wordlist: 
        print(str(w)+ " : "+ str(ps.stem(w)))

In [21]:
stemmer(words)

program : program
programs : program
programer : program
programing : program
programers : program


In [22]:
def stemmer(sentence):
    wordlist = word_tokenize(sentence)
    for w in wordlist: 
        print(str(w)+ " : "+ str(ps.stem(w)))

In [23]:
sentence1 = "Programmers program using programming languages"
sentence2 = "He fights using the powerful forces that he forced out of the force"

In [24]:
stemmer(sentence1)
print("\n\n")
stemmer(sentence2)

Programmers : programm
program : program
using : use
programming : program
languages : languag



He : He
fights : fight
using : use
the : the
powerful : power
forces : forc
that : that
he : he
forced : forc
out : out
of : of
the : the
force : forc


# 3) VECTORIZERS:

______________________________________________________________________________________________________________________________
Count Vectorizer:

In [25]:
from sklearn.feature_extraction.text import CountVectorizer

In [26]:
corpus = [
     'This is the first document.',
     'This document is the second document.',
     'And this is the third one.',
     'Is this the first document?',
]

In [38]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
for i in vectorizer.get_feature_names():
    print(str(i))

and
document
first
is
one
second
the
third
this


In [31]:
print(X.toarray())

[[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]


________________________________________________________________________________________________________________________________
Tf Idf Vectorizer:

In [32]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [37]:
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(corpus)
for i in vectorizer.get_feature_names():
    print(str(i))

and
document
first
is
one
second
the
third
this


In [39]:
print(X.shape)

(4, 9)
